language: ruby
cache: bundler
rvm:
  - 2.6.3
services:
  - postgresql
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rails webpacker:install
  - bundle exec rails webpacker:compile RAILS_ENV=test
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
deploy:
  provider: heroku
  api_key:
    secure: kxOtL7T3Jzu+nBp78HGtdTLAtVvfHQYPBO1eQO60UB5fHflDI9P7Ll2U+6vH09rag/UL0VjOi6XDAecQFXllG6SrB40DUVVwDeviFi41NqQPw1a735sG3ua4B9H1LGMirHDfr8KNJKdLK9n+i2XxkQurM679whTI/XP3zdgkyODURVhSE4Hy4TeyzcntzGAvAQbjfF0yC+M6iHivTaFAgHbC2oIpHyMCK4gIT/jkctDRslWi9DcyK8t6CWxNTg70DNZDu7f/ClA4lLuOV6v6kZfCXqC72wbx1ldox+0Nm9EywebAxzUK3DmyHP8jSBmc+Qb4pJ2nhzRSD2uiWSf2LhRHjmne+Gf3y74449B9UIpFQtO7YWfzHF1no+Hy7aepWSzHRXHlHU1TyGE92gaNMQkY+BaTXrybCTF73lICJbrf000khHN1cw1Xi1LY/sdGKstt74d6R5uyLtqh9r7VWJ4NuUC0oi9e18HfRcL5HMAyenR5pnU4YlqnQ3Hq/0yR/8tyOH3VmRORHKCKnpk2HUtjZv9rwzdGHTCYjzYbj+1kUSULSO0IxYJj7wbT5NQehaiFQ2iGLYknym+UauUAJLZwEfzeF0uyffdylzoKq7RhowzQoEjxumFqggIECTx/tlDWxT2nniHvxABcwchaI0ky4fUi3b+3t0aU1BJkWNs=
  app: hocq2
  on:
    repo: BlazingBBQ/hocq2
